---
# tasks file for installing etcd on centos7

- name: install etcd releated package
  yum: name={{ item }} state=present
  with_items:
    - etcd

- name: include tls.yml
  include: tls.yml
  when: etcd_tls_enabled is defined and etcd_tls_enabled == 'true'

- name: template /etc/etcd/etcd.conf
  template: src=etc/etcd/etcd.conf.j2 dest=/etc/etcd/etcd.conf mode=644 backup=yes
  notify: restart etcd

- name: start and enable etcd
  service: name=etcd state=started enabled=yes
